version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # smaller project so this is fine
      - dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
