version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch:
        applies-to: security-updates
        patterns:
          - "@angular*"
        update-types:
          - "patch"
          - "minor"
        group-by: dependency-name


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
