version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # smaller project so this is fine
      - dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
      - dependency-type: "all"
        update-types:
          - "major"
        allow:
          - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
