name: deploy-docusaurus

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Set up Yarn instead of just Node.js (this uses Yarn's latest version)
      - name: Set up Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn' # Enable caching for yarn dependencies

      # Install dependencies and build the Docusaurus website
      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile # Ensures you’re using the exact dependencies listed in yarn.lock
          yarn build # Runs the Docusaurus build command

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
